# process 事件监听
## 进程相关事件
### 事件：`beforeExit`
当 Node 事件循环即将结束时，且没有其他待处理的任务时，会触发`beforeExit`事件。可以在这个事件中执行一些异步操作，Node 会在这些操作完成后再退出。
```javascript
process.on('beforeExit', (code) => {
  console.log('Process beforeExit event with code: ', code)
  // 可以在这里执行一些异步操作
  setTimeout(() => {
    console.log('异步操作完成')
  }, 100)
})

console.log('程序执行完毕')
```
在这个示例中，`beforeExit`事件触发后，Node 会等待`setTimeout`中的异步操作完成，然后再退出程序。

也就是说开启了新一轮的事件循环，当`beforeExit`事件中有异步操作时，Node 会开启新一轮的事件循环来处理这些异步操作。如果在事件处理函数中注册了新的异步任务（如`setTimeout`、`setImmediate`、I/O 操作等），Node 会继续处理这些任务，直到事件循环中没有待处理的任务为止。
### 事件：`exit`
当 Node 进程即将退出时，会触发`exit`事件。可以在这个事件中执行一些同步操作（注意：不能执行异步操作），例如清理资源或记录日志。
```javascript
process.on('exit', (code) => {
  console.log('进程即将退出，退出码: ', code)
  // 这里可以执行一些同步操作
  // 注意：不能在这里执行异步操作
})

console.log('程序执行完毕')
```
需要注意的是：
- `exit`事件的回调函数中不能包含异步操作，因为在`exit`事件触发后，事件循环已经停止，任何异步操作都不会被执行。
- `exit`事件的回调函数接收一个参数`code`，表示进程的退出码。正常退出时，退出码为 0。

#### 与`disconnect`、`beforeExit`事件的执行顺序
```javascript
// 父进程 parent.js
const { fork } = require('child_process')
const child = fork('child.js')

child.on('disconnect', () => {
  console.log('父进程：子进程已断开连接')
})

process.on('beforeExit', (code) => {
  console.log('父进程：beforeExit 事件，退出码: ', code)
  // 可以在这里执行一些异步操作
  setTimeout(() => {
    console.log('父进程：异步操作完成')
  }, 100)
})

process.on('exit', (code) => {
  console.log('父进程：exit 事件，退出码: ', code)
  // 这里可以执行一些同步操作
})

setTimeout(() => {
  child.disconnect()
}, 2000)


// 子进程 child.js
process.on('disconnect', () => {
  console.log('子进程：与父进程的连接已断开')
})

// 保持子进程运行
setInterval(() => {
  console.log('子进程：仍在运行')
}, 1000)
```
执行顺序如下：
1. `disconnect`事件：
   1. 在父进程中，2 秒后调用`child.disconnect()`，触发父进程和子进程的`disconnect`事件。
   2. 输出 "父进程：子进程已断开连接" 和 "子进程：与父进程的连接已断开"。
2. `beforeExit`事件：
   1. 当父进程的事件循环即将结束且没有其他待处理任务时，触发 beforeExit 事件。
   2. 输出 "父进程：beforeExit 事件，退出码: 0"。
   3. 执行异步操作，输出 "父进程：异步操作完成"。
3. exit 事件：
   1. 在父进程即将退出时，触发 exit 事件。
输出 "父进程：exit 事件，退出码: 0"。

### 信号事件
`process`对象可以监听操作系统信号事件。

信号是操作系统用来通知进程某些事件发生的机制，例如终止进程、暂停进程等。可以使用`process.on`方法来监听这些信号事件，并在信号事件触发时执行相应的处理逻辑。

以下是一些常见的信号及其说明：
- SIGINT：通常在用户按下 Ctrl+C 时触发，用于中断进程。
- SIGTERM：用于请求进程终止。
- SIGHUP：通常在终端关闭时触发。
- SIGUSR1 和 SIGUSR2：用户自定义信号。

参数（用处不大）：
- `single`：信号名称
- `singleCode`：信号代码

```javascript
// 监听 SIGINT 信号（通常在用户按下 Ctrl+C 时触发）
process.on('SIGINT', () => {
    console.log('收到 SIGINT 信号，进程即将退出')
    // 执行一些清理操作
    process.exit(0)
})

// 监听 SIGTERM 信号
process.on('SIGTERM', () => {
    console.log('收到 SIGTERM 信号，进程即将退出')
    // 执行一些清理操作
    process.exit(0)
})

// 监听 SIGHUP 信号
process.on('SIGHUP', () => {
    console.log('收到 SIGHUP 信号')
    // 执行一些操作，例如重新加载配置
})

// 模拟发送 SIGINT 信号
setTimeout(() => {
    process.kill(process.pid, 'SIGINT')
}, 5000)

// 模拟发送 SIGTERM 信号
setTimeout(() => {
    process.kill(process.pid, 'SIGTERM')
}, 10000)

// 监听自定义信号（通常在用户按下 Ctrl+C 时触发）
process.on('SIGUSR1', () => {
    console.log('收到自定义信号，进程即将退出')
    // 执行一些清理操作
    process.exit(0)
})

// 模拟发送 自定义信号
setTimeout(() => {
    process.kill(process.pid, 'SIGUSR1')
}, 1000)

```

## IPC相关事件
### 事件：`message`
用于在父进程和子进程之间进行消息传递。当一个进程接收到来自另一个进程的消息时，会触发`message`事件。
### 事件：`disconnect`
当 Node 进程与其父进程之间的 IPC 通道被关闭时，会触发`disconnect`事件。通常，这个事件在使用`child_process`模块创建子进程时会用到。
```javascript
// 父进程 parent.js
const { fork } = require('child_process')
const child = fork('child.js')

child.on('disconnect', () => {
  console.log('子进程已断开连接')
})

// 模拟一段时间后断开连接
setTimeout(() => {
  child.disconnect()
}, 2000)


// 子进程 child.js
process.on('disconnect', () => {
  console.log('与父进程的连接已断开')
})

// 保持子进程运行
setInterval(() => {
  console.log('子进程仍在运行')
}, 1000)
```
## 异常捕获事件
### 捕获`Promise`异常
#### 事件：`multipleResolves`
当同一个`Promise`被多次`resolve`或`reject`时，会触发`multipleResolves`事件。这种情况通常是由于代码逻辑错误引起的，可以监听这个事件来捕获并处理这些情况。

参数：
- `type`：类型，可以是`'resolve'`或`'reject'`
- `promise`：被多次`resolve`或`reject`的`Promise`对象
- `reason`：`resolve`、`reject`的值
```javascript
process.on('multipleResolves', (type, promise, reason) => {
    console.error(`Promise 多次解析或拒绝: ${type}`, promise, reason)
    // 这里可以执行一些处理逻辑，例如记录日志或抛出错误
})

const promise = new Promise((resolve, reject) => {
    resolve('第一次 resolve')
    resolve('第二次 resolve') // 这将触发 multipleResolves 事件
    reject('第一次 reject') // 这也将触发 multipleResolves 事件
})

promise
    .then(value => {
        console.log('Promise 解析值:', value)
    })
    .catch(error => {
        console.error('Promise 拒绝原因:', error)
    })

// Promise 多次解析或拒绝: resolve Promise { '第一次解析' } 第二次解析
// Promise 多次解析或拒绝: reject Promise { '第一次解析' } 拒绝
// Promise 解析值: 第一次解析
```
#### 事件：`rejectionHandled`
当一个`Promise`被`rejected`且没有被捕获（`catch`），然后在稍后某个时间点被捕获时，会触发`rejectionHandled`事件。

通过监听`rejectionHandled`事件，可以检测那些最初未处理的`Promise`拒绝情况，并在稍后处理的这些`rejected`。这有助于发现和处理代码中的潜在问题。

参数：
- `promise`：被拒绝且稍后被处理的 Promise 对象。
```javascript
process.on('rejectionHandled', promise => {
    console.log('Promise 拒绝被延时捕获:', promise)
})

const promise = new Promise((resolve, reject) => {
    reject('Promise 被拒绝')
})

// 延迟处理 Promise 拒绝
setTimeout(() => {
    promise.catch(error => {
        console.log('捕获到的错误:', error)
    })
}, 1000)

// 捕获到的错误: Promise 被拒绝
// Promise 拒绝被延时捕获: Promise { <rejected> 'Promise 被拒绝' }
```
#### 事件：`unhandledRejection`
当一个`Promise`被`rejected`且没有被捕获时，会触发`unhandledRejection`事件。这个事件可以用来捕获和处理未被捕获的`Promise`的`rejected`，从而防止程序崩溃。但应尽量避免依赖这种方式进行错误处理。

参数：
- `reason`：`Promise`被`rejected`的原因
- `promise`：被拒绝且未被捕获的`Promise`对象
```javascript
process.on('unhandledRejection', (reason, promise) => {
    console.error('未捕获的 Promise 拒绝:', promise, '原因:', reason)
    // 这里可以执行一些清理操作，例如记录日志或释放资源
    // 然后退出进程
    process.exit(1)
})

// 模拟一个未捕获的 Promise 拒绝
new Promise((resolve, reject) => {
    reject('模拟的未捕获拒绝')
})
```
### 捕获同步同步
#### 事件：`uncaughtException`
当一个异常未被捕获时，会触发`uncaughtException`事件。这个事件可以用来捕获和处理未被捕获的异常，从而防止程序崩溃。

参数：
- `err`：未捕获的异常对象。
```javascript
process.on('uncaughtException', err => {
    console.error('未捕获的异常:', err)
    // 这里可以执行一些清理操作，例如记录日志或释放资源
    // 然后退出进程
    process.exit(1)
})

// 模拟一个未捕获的异常
setTimeout(() => {
    throw new Error('模拟的未捕获异常')
}, 1000)

// 打印：
/**
 * 未捕获的异常: Error: 模拟的未捕获异常
 *   at Timeout._onTimeout (/index.js:10:11)
 *   at listOnTimeout (internal/timers.js:554:17)
 *   at processTimers (internal/timers.js:497:7)
 */
```
需要注意的是，使用`uncaughtException`事件来处理未捕获的异常是一种应急措施，不能作为常规的错误处理机制。更好的做法是通过适当的错误处理和捕获机制来管理异常。
#### 事件：`uncaughtExceptionMonitor`
用于监控未捕获的异常。与`uncaughtException`事件不同，`uncaughtExceptionMonitor`事件不会影响异常的默认处理行为。

也就是说即使触发了`uncaughtExceptionMonitor`事件，进程也会继续抛出异常。它主要用于监控和记录未捕获的异常，而不是处理它们。
```javascript
process.on('uncaughtExceptionMonitor', err => {
    console.error('监控到未捕获的异常:', err)
    // 这里可以执行一些监控或记录操作，例如记录日志
})

// 模拟一个未捕获的异常
setTimeout(() => {
    throw new Error('模拟的未捕获异常')
}, 1000)

/** 打印内容如下：
    监控到未捕获的异常: Error: 模拟的未捕获异常
        at Timeout._onTimeout (//index.js:8:11)
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7)
    /index.js:8
        throw new Error('模拟的未捕获异常')
        ^

    Error: 模拟的未捕获异常
        at Timeout._onTimeout (/index.js:8:11)
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7)
 */
```
#### 事件：`warning`
用于捕获和处理进程中的警告信息。警告通常是非致命性的错误或潜在问题，Node 会通过`warning`事件发出警告。

参数：
- `warning`：一个 Error 对象，包含以下属性：
  - `name`：警告的名称。
  - `message`：警告的详细信息。
  - `stack`：警告的堆栈信息。
```javascript
process.on('warning', warning => {
    console.warn('警告信息:', warning.name)
    console.warn('警告详情:', warning.message)
    console.warn('警告堆栈:', warning.stack)
})

// 模拟一个警告
process.emitWarning('这是一个自定义警告', {
    code: 'CUSTOM_WARNING',
    detail: '这是警告的详细信息'
})
```
- 自定义警告：可以使用`process.emitWarning`方法手动触发警告，并提供自定义的警告信息。